services:
  db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_LOGGING_COLLECTOR: "on"
      POSTGRES_LOG_STATEMENT: "all"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: ["uvicorn", "apps.telegram_bot.main:app", "--host", "0.0.0.0", "--port", "8080"]
    ports:
      - 8080:8080
    volumes:
      - .:/app:delegated
    working_dir: /app

volumes:
  pgdata:
